services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Discutea\MediaBundle\:
        resource: '../../*'
        exclude: '../../*/{vendor,DependencyInjection,Tests}'

    Discutea\MediaBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Discutea\MediaBundle\Services\Config:
        arguments:
            $config: '%discutea_media.config%'

    Discutea\MediaBundle\Listener\MediaContentListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: addContent }
